version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/patientdb
      - SPRING_DATASOURCE_USERNAME=patientuser
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SQL_INIT_MODE=never
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=false
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=patientdb
      - POSTGRES_USER=patientuser
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patientuser -d patientdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: patientlookup_postgres_data